### ISSUE TITLE
Not detecting default credentials on Oracle 11g2

### ISSUE THREAD

**Issue by claudijd** [SpiderLabs/net-tns#18]
When checking default credentials on Oracle 11g2, there is a NoMethod bug in the parsing of the crypto response.

>> require 'net/tns'
=> true
>> require 'net/tti'
=> true
>> tti_client = Net::TTI::Client.new
=> #<Net::TTI::Client:0x007fadab122ab8>
>> tti_client.connect( :host => "10.25.244.96", :sid => "orcl11g2" )
tti_client.authenticate( "test", "t3sT" )
=> true
>> tti_client.authenticate( "test", "t3sT" )
NoMethodError: undefined method `chr' for true:TrueClass
	from /Users/jclaudius/code/net-tns/lib/net/tti/crypto.rb:141:in `block in create_combined_session_key_hash_11g'
	from /Users/jclaudius/code/net-tns/lib/net/tti/crypto.rb:140:in `each'
	from /Users/jclaudius/code/net-tns/lib/net/tti/crypto.rb:140:in `create_combined_session_key_hash_11g'
	from /Users/jclaudius/code/net-tns/lib/net/tti/crypto.rb:68:in `get_11g_auth_values'
	from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:72:in `get_auth_request'
	from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:37:in `authenticate'
	from (irb):5
	from /Users/jclaudius/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'

**Comment by woodbusy** [comment]
I think I remember seeing this before, but I no longer have access to an 11g R2 server. Could you add a pcap or a branch with added (failing) specs?

**Comment by claudijd** [comment]
I just sent you a PCAP of the above activity.  Sorry for the delay.

**Comment by mrakhmanov** [comment]
The server (11g2) sends 10g style response to the client because the negotiation does not fully follow 11g2 protocol. Acting differently based upon auth_sesskey.length may help to solve this particular problem. There is a another issue: authentication code is not reached for many targets having different platform, architecture, and version different from what the client has. TTIDTY message exchange phase which happens just before AUTH does not complete successfully.

**Comment by woodbusy** [comment]
@mrakhmanov thanks for your wisdom. I appreciate it! I'm not surprised that there are other issues, given my limited testing environment and knowledge of TTI - DTY especially is almost a complete mystery to me. If you have any more specifics you could comment on or create issues for, that would be great.

@claudijd I took @mrakhmanov's approach with the code in #20. If you (or anyone else with an 11g2 server) could try it out, that would be great.

**Comment by claudijd** [comment]
@woodbusy I just tested against against @mrakhmanov's 11g2 test box (the original test target) and it seems to get past the crypto bug now, but it throws proto exceptions.  Here's my IRB output from testing...

    ~/code/net-tns ((detached from upstream/11g_r2)) $ irb -I lib
    >> tti_client = Net::TTI::Client.new
    NameError: uninitialized constant Net
     from (irb):1
     from /Users/jclaudius/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
    >> require 'net/tns'
    => true
    >> require 'net/tti'
    => true
    >> tti_client = Net::TTI::Client.new
    => #<Net::TTI::Client:0x007fea6b87b5d8>
    >> tti_client.connect( :host => "10.25.244.96", :sid => "orcl11g2" )

    => true
    >> 
    ?> tti_client.authenticate( "test", "NOT_THE_PASSWORD" )
    Net::TTI::Exceptions::ProtocolException: Unexpected AUTH_SESSKEY length: 32
     from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:74:in `get_auth_request'
     from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:37:in `authenticate'
     from (irb):7
     from /Users/jclaudius/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'

FWIW, I get the same error for valid (as I know them) and invalid creds.  @mrakhmanov any chance the creds changed recently from what was previously provided?

**Comment by claudijd** [comment]
@mrakhmanov proposed some changes in #21 

I tested them here against an 11g2 target, it seems to handle it better to imply I've got the wrong creds.  @mrakhmanov I will confirm with you out of band with what creds I'm using.

    >> require 'net/tns'
    => true
    >> require 'net/tti'
    => true
    >> 
    ?> tti_client = Net::TTI::Client.new
    => #<Net::TTI::Client:0x007f8263883aa0>
    >> tti_client.connect( :host => "10.25.244.96", :sid => "orcl11g2" )
    => true
    >> tti_client.authenticate( "test", "bananas" )
    Net::TTI::Exceptions::InvalidCredentialsError: ORA-01017: invalid username/password; logon denied

    	from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:43:in `rescue in authenticate'
    	from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:31:in `authenticate'
    	from (irb):6
    	from /Users/jclaudius/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'

**Comment by claudijd** [comment]
Confirmed with @mrakhmanov that I had the wrong creds, here's successful auth using his proposed code...

    ~/code/net-tns ((detached from mrakhmanov/master)) $ irb -I lib
    >> require 'net/tns'
    => true
    >> require 'net/tti'
    => true
    >> 
    ?> tti_client = Net::TTI::Client.new
    => #<Net::TTI::Client:0x007fb50aa77b48>
    >> tti_client.connect( :host => "10.25.244.96", :sid => "orcl11g2" )
    tti_client.authenticate( "test", "t3sT" )

    => true
    >> tti_client.authenticate( "test", "THE_ACTUAL_PASSWORD" )
    => true

Also, for giggles, I tested @woodbusy 's proposed code here too and get the same session key length issue as before:

    >> require 'net/tns'
    => true
    >> require 'net/tti'
    => true
    >> 
    ?> tti_client = Net::TTI::Client.new
    => #<Net::TTI::Client:0x007fa0c208afd8>
    >> tti_client.connect( :host => "10.25.244.96", :sid => "orcl11g2" )
    => true
    >> tti_client.authenticate( "test", "t3sT" )
    Net::TTI::Exceptions::ProtocolException: Unexpected AUTH_SESSKEY length: 32
    	from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:74:in `get_auth_request'
    	from /Users/jclaudius/code/net-tns/lib/net/tti/client.rb:37:in `authenticate'
    	from (irb):6
    	from /Users/jclaudius/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'

It seems @mrakhmanov's changes are more accurate, but the specs will need to be updated to get them passing.

**Comment by claudijd** [comment]
Additionally, we should probably also validate that we can check default creds on a range of supported Oracle DB endpoints.  I'm not that familiar with Oracle versions to determine what we should test against, but open to suggestions.

**Comment by woodbusy** [comment]
@claudijd yeah, looks like I'm bad at math (16 and 24 in the `case` should have been 32 and 48). Going forward, I think that @mrakhmanov's changes are going to be a huge improvement, so I'm going to focus on that path rather than #20.
